version: '2'
services:
  JuiceServer:
    image: 'bkimminich/juice-shop:latest'
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
  kali:
    image: 'daindragon2/kali_desktop:latest'
    stdin_open: true
    tty: true
    ports:
      - '5901:5901'
    cap_add:
      - ALL
networks: {}
