version: '2'
services:
  WebGoat:
    image: 'vimagick/webgoat:latest'
    stdin_open: true
    tty: true
    ports:
      - '9999:8080'
  kali:
    image: 'dockersecplayground/kali:latest'
    stdin_open: true
    tty: true
    ports:
      - '10000:23'
    cap_add:
      - ALL
    privileged: true
networks: {}
