version: '2'
services:
  hackme:
    image: 'dockersecplayground/ubuntu32:latest'
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
  kali:
    image: 'daindragon2/kali_desktop:latest'
    stdin_open: true
    tty: true
    ports:
      - '5901:5901'
    cap_add:
      - ALL
networks: {}
