version: '2'
services:
  provaKali:
    image: 'dockersecplayground/kali:latest'
    stdin_open: true
    tty: true
    ports:
      - '10000:4200'
    networks:
      network:
        ipv4_address: 192.168.1.2
    cap_add:
      - NET_ADMIN
  router:
    image: 'dockersecplayground/alpine:latest'
    stdin_open: true
    tty: true
    networks:
      network:
        ipv4_address: 192.168.1.3
      twonetwork:
        ipv4_address: 192.168.2.2
    cap_add:
      - NET_ADMIN
  entry:
    image: 'dockersecplayground/alpine:latest'
    stdin_open: true
    tty: true
    networks:
      twonetwork:
        ipv4_address: 192.168.2.3
    cap_add:
      - NET_ADMIN
networks:
  network:
    ipam:
      config:
        - subnet: 192.168.1.1/24
  twonetwork:
    ipam:
      config:
        - subnet: 192.168.2.1/24
