version: '2'
services:
  website:
    image: 'dockersecplayground/linode_lamp:latest'
    stdin_open: true
    tty: true
    ports:
      - '11000:80'
    volumes:
      - './website:/var/www/example.com/public_html'
    cap_add:
      - NET_ADMIN
networks: {}
