version: '2'
services:
  WebServer:
    image: 'dockersecplayground/linode_lamp:latest'
    stdin_open: true
    tty: true
    ports:
      - '11110:80'
    cap_add:
      - NET_ADMIN
  kali:
    image: 'daindragon2/kali_desktop:latest'
    stdin_open: true
    tty: true
    ports:
      - '5901:5901'
    cap_add:
      - ALL
networks: {}
